http:
  port: "8081"
  
sdfc:
  username: "misbah@ammar.sf"
  password: "Miss@salesforce1903"
  token: "wEsbNWx0vB84AT0u6OAnnXBmt"

file: 
  Dir: "/Users/ammarmansuri/Desktop/My documents/MuleSoft/APDevFundamentals4.4_studentFiles_SP_27jun2022/resources"
  
db:
  host: "mudb.learn.mulesoft.com"
  port: "3306"
  user: "mule"
  password: "mule"
  database: "training"  